services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=barber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    restart: always

  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 barberflow.wsgi:application
    volumes:
      - ./backend:/app
      - backend_static:/app/backend_static
      - media_data:/app/media
    environment:
      - DEBUG=False
      - DB_NAME=barber
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    restart: always

  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - backend_static:/app/backend_static
      - media_data:/app/media
    restart: always

volumes:
  postgres_data:
  backend_static:
  media_data:
